### ISSUE TITLE
RuntimeError: Couldn't delete node from stored nodes hash in `dijkstra_shortest_path`

### ISSUE THREAD

**Issue by gorn** [monora/rgl#23]
The following code
```
g = RGL::AdjacencyGraph[9,14, 13,19, 17,20, 2,25, 10,25, 4,25, 23,25, 22,25, 9,22, 13,21, 6,17, 2,7, 3,10, 4,11, 5,23]
g.dijkstra_shortest_path(Hash.new(1),25,14)
```
fails with "RuntimeError: Couldn't delete node from stored nodes hash" with backtrace:
```
         # /var/lib/gems/2.1.0/gems/algorithms-0.6.1/lib/containers/heap.rb:236:in `pop'
         # /var/lib/gems/2.1.0/gems/rgl-0.5.1/lib/rgl/dijkstra.rb:64:in `relax_edges'
         # /var/lib/gems/2.1.0/gems/rgl-0.5.1/lib/rgl/dijkstra.rb:32:in `shortest_path'
         # /var/lib/gems/2.1.0/gems/rgl-0.5.1/lib/rgl/dijkstra.rb:141:in `dijkstra_shortest_path'
```

**Comment by monora** [comment]
Fixed by #28.
